lines2hsegs:zs_lines2hsegs.cpp 
	g++ -I. -I../shplib ../shplib/dbfopen.c ../shplib/safileio.c ../shplib/sbnsearch.c ../shplib/shpopen.c ../shplib/shptree.c  zs_lines2hsegs.cpp -o lines2hsegs -std=c++0x
