shp2lines:zonalstat_shp2lines.cpp 
	g++ -I. -I../shplib ../shplib/dbfopen.c ../shplib/safileio.c ../shplib/sbnsearch.c ../shplib/shpopen.c ../shplib/shptree.c  zonalstat_shp2lines.cpp -o shp2lines -std=c++0x
